# Generated by Django 4.2.7 on 2023-11-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FI', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_smoke', models.BooleanField(default=False)),
                ('birthday', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
