# Generated by Django 4.2.7 on 2023-11-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_student_delete_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('publication', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
    ]
